default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("POSTGIS_URL") %>

development:
  <<: *default
  database: neighborhood_development

test:
  <<: *default
  database: neighborhood_test

production:
  <<: *default
  database: neighborhood_production
  username: neighborhood
  password: <%= ENV["NEIGHBORHOOD_DATABASE_PASSWORD"] %>
